### ISSUE TITLE
Have no usage pakage

### ISSUE THREAD

**Issue by foxhujm** [subosito/twilio#5]
* util.go:27
* have not find this pakage "github.com/subosito/figo"

**Comment by bsdlp** [comment]
`go get github.com/subosito/figo`

**Comment by bsdlp** [comment]
@subosito since it looks like only this package is importing figo, might be a good idea to include figo as a subpackage of this one so that users don't have to deal with pulling down dependencies.

**Comment by subosito** [comment]
@bsdlp Thanks for the suggestion Jon, just made the change on ed723a9b253696286cc657e5ca4d251dcc391f4c.

Hope it also fix your issue @foxhujm :)
